---
title: "01_data_prep"
author: "Jagadeesh Puvvula"
date: "2023-07-21"
output: pdf_document
---

```{r}
#! use R 4.2.2
Sys.setenv(R_VERSION="4.2.2")

library(pacman)
pacman::p_load(tidyverse, janitor, reshape2, SuperLearner, caret)
dat_origin<-  read_csv("E:/BBK17/pj/data_2023apr/obs_w_outcome/home_mirec_w_out.csv") |>
  mutate(pb = if_else(cohort == "1", pb * 10, pb))
data <- "E:/BBK17/pj/basc_brief_analy/data/"
result<- "E:/BBK17/pj/basc_brief_analy/result/"
analy_dat<- "E:/BBK17/pj/basc_brief_analy/analy_dat/"
```

#Select variables for BASC and BRIEF analysis 
```{r}
dat_basc<- dat_origin |>
  clean_names()|>
  select(-c(43:45))|>
  rename(Pb=pb, Hg=hg, DMA=dma, DDE= dde, PBDE_47 = pbde47,
         PCB_118=pcb118, PCB_138=pcb138, PCB_153=pcb153,
         PCB_180=pcb180, PFHxS=pfhxs, PFOA=pfoa, PFOS=pfos,
         BCEtP=bcetp, BDCPP=bdcpp, DBuP=dbup, DPhP=dphp,
         TCS=tcs, BPA=bpa, MBP=mbp, MBZP=mbzp, MCPP=mcpp,
         sigma_DEHP=dehp, MEP=mep, MIBP=mibp, di_Ethyl_OP=op_de,
         di_Methyl_OP=op_dm, B_PB=b_pb, M_PB=m_pb, P_PB=p_pb, city=center,
         mom_edu_cat=edu3)|>
  mutate(race_bin = if_else(race == "white", 1, 2),
         sex = if_else(sex == "Male", 1, 2)) |>
  filter(if_all(43:47, ~ !is.na(.) & !grepl("^\\s*$", .) & !grepl("^\\.$", .))) #if_any didnt work here
```

# export data version for behavioral outcome analysis (all obs with outcome - has missing exposures)
```{r}
write_csv(dat_basc, paste0(data, "dat_basc.csv"))
```

#get subset with all outcomes and exposures
```{r}
dat_basc<- read_csv(paste0(data, "dat_basc.csv"))

dat_basc_all_exp<- dat_basc |>
  filter(if_all(c(4:32), ~ !is.na(.) & !grepl("^\\s*$", .) & !grepl("^\\.$", .))) |>
  mutate(mom_edu_cat = if_else(is.na(mom_edu_cat), 2, mom_edu_cat)) |> # replaced with category-2 (dominant)
  select(-c("b_length", "b_wght", "race"))


# 100 obs missing HOME score
x<- dat_basc_all_exp |>
  group_by(cohort, sex, city) |>
  summarise(missing_home = sum(is.na(home_score_total)))
```

#missing data summary
```{r}
dat_miss<- missing_data_summary(dat_basc_all_exp) #ref999
```


#correlations
```{r}
dat_cor<- dat_basc_all_exp |> select(c(4:33, 37:39, 41:45)) |> #38 = HOME score
  drop_na()

cormat <- round(x=cor(dat_cor, method = "spearman", use = "complete.obs"), digits = 2) |>
  melt() |> 
  clean_names()

ggplot(cormat, aes(x = var2, y = var1, fill = value)) + #, label = value
  geom_tile(color = "white") +
  #geom_text(color = "black", size = 3, vjust = 1) +
  scale_fill_gradient2(low = "red", high = "blue", mid = "white",
                       midpoint = 0,
                       limit = c(-1, 1), space = "Lab",
                       name = "Spearman Correlation | HOME & MIREC [n=704]") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 11, hjust = 1),
        axis.text.y = element_text(angle = 0, vjust = 0.5, size = 11, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom", legend.box = "horizontal") +
  coord_fixed() #+
  # add vertical and horizontal lines to separate variable groups
  #geom_vline(xintercept = c(0, 3.5, 9.5, 12.5,  16.5, 19.5, 21.5, 27.5, 29.5), color = "black", size=1.25) +
  #geom_hline(yintercept = c(0, 3.5, 9.5, 12.5, 16.5, 19.5, 21.5, 27.5, 29.5), color = "black", size=1.25) 
```

#Impute unmeasured HOME score data using SuperLearner
```{r}
pred_var<- "home_score_total"
dat_pred_v1 <- impute_missing(dat_basc_all_exp, {{pred_var}})

#filter unknown data for predictions
pred_set <- dat_pred_v1 |>
  filter(is.na(dat_pred_v1[[pred_var]])) |>
  select(-c(2:3))


#for training the prediction model
dat_n <- dat_pred_v1 |> drop_na() |>
  select(-c(1:3))

set.seed(123, "L'Ecuyer-CMRG")
indx<- sample(nrow(dat_n), round(0.75*nrow(dat_n)))
train<- dat_n[indx,]
test<- dat_n[-indx,]

y_train<- train[[pred_var]]
x_train<- train[, -which(colnames(train) == pred_var)]

x_test <- as.matrix(test[, -which(colnames(test) == pred_var)])
y_test <- as.matrix(test[[pred_var]])

#model object
sl.obj2<- SuperLearner(y_train, x_train, family = gaussian(), 
                       SL.library = c("SL.mean", "SL.xgboost", "SL.gbm"))
#model validation to get MSE
validation<- predict(sl.obj2, test[, -which(colnames(test) == pred_var)])


#get predictions: Input - > variable column number being predicted, variable name and rounding
x <- generate_x(sl.obj = sl.obj2, pred_set = pred_set, id_col = 1, 
                pred_var = pred_var, rounding = 1)


#replaces NA values with the predicted values
original <- replace_values(x, dat_basc_all_exp)
```

#export dataset with inputed HOME score - no more NA values 
```{r}
write_csv(original, paste0(data, "basc_imputed.csv"))
```










