---
title: "888_scatter_plots"
author: "Jagadeesh Puvvula"
date: "2024-07-09"
output: pdf_document
---

```{r}
dat<- read_csv(paste0(data, "basc_imputed.csv")) |>
  select(c(Pb, Hg, DMA, DDE, PBDE_47, PCB_118, PCB_138, PCB_153, PCB_180,
          PFHxS, PFOA, PFOS, BCEtP, BDCPP, DBuP, DPhP, TCS, BPA, MBP, MBZP,
          MCPP, sigma_DEHP, MEP, MIBP, di_Ethyl_OP, di_Methyl_OP, 
          B_PB, M_PB, P_PB, cotinine, home_score_total, mom_age, 
          cohort, city, sex, race_bin,  mom_edu_cat, parity_n,
          basc_ext, basc_inz, basc_bsi, brief_wm, brief_po)) |>
  mutate(across(all_of(c("cohort", "city", "sex", "race_bin", 
                         "parity_n", "mom_edu_cat")), as.factor),
         sex = ifelse(sex == "1", "Male", "Female")) |>
  mutate_at(vars(1:30), ~log10(.+0.0000001)) |>
  rename_with(~ paste0("log_", .x), 1:30) |>
  filter(!(basc_ext == 0 | basc_inz == 0 | basc_bsi == 0 | brief_wm == 0 | brief_po == 0))
```

```{r}
x<- lm(basc_ext ~ log_PFOA + log_cotinine+ home_score_total+ mom_age+ 
       cohort+ city+ sex+ race_bin+  mom_edu_cat+ parity_n, data=dat)
```


```{r}
dat_plt<- dat|>
  select(c("log_PFHxS", "log_PFOA", "log_PFOS",
           "basc_ext", "basc_inz", "basc_bsi", "brief_wm", "brief_po", "sex")) |>
  filter(!(basc_ext == 0 | basc_inz == 0 | basc_bsi == 0 | brief_wm == 0 | brief_po == 0))

create_scatter_plots <- function(x_vars, y_vars, data) {
  
  plot_list <- list()
  
  for (x_var in x_vars) {
    for (y_var in y_vars) {
      plot <- ggplot(data, aes_string(x = x_var, y = y_var)) +
        geom_point(size = 1) +
        stat_smooth(method = "lm", 
                    formula = y ~ x,
                    se = TRUE,  colour = "gray50") +
        theme_minimal()
      
      plot_list[[paste(x_var, y_var, sep = "_")]] <- plot
    }
  }
  
  # Convert list of plots to arrange them using grid.arrange
  do.call(grid.arrange, c(plot_list, nrow = length(x_vars)))
}

create_scatter_plots(x_vars = c("log_PFHxS", "log_PFOA", "log_PFOS"), 
                 y_vars = c("basc_ext", "basc_inz", "basc_bsi", "brief_wm", "brief_po"), 
                 data = dat_plt)
```

